# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7f6d1be1943a8c919bf95b16fa3732a97f8ccde02b643310d3ec6cfe53e359eef8d675653e0a8bedbf580cd3be29d214b3ff1b6dace6e099e11e95bf3898d47

test:
  secret_key_base: 7b05d952f24dd200f7706e907bdea2bbbd8efb3e4d97ae761b37507c9d1e5e32d91b6fe22ec23956b1de4499d2c00259da223644a9ee469b87ea6f45fe859411

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
